spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2-console

security:
  jwt:
    secret: SyamKumar
    expiration: 60000 # JWT expiration in milliseconds
